### ISSUE TITLE
ERROR: YouTube said: Unable to extract video data

### ISSUE THREAD

**Issue by Puffin05** [l1ving/youtube-dl#20]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.10.30**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=HvGX69KCok0', u'-f', u'299', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.10.30
[debug] Python version 2.7.10 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] HvGX69KCok0: Downloading webpage
ERROR: HvGX69KCok0: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1779, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: HvGX69KCok0: YouTube said: Unable to extract video data

## Description

Attempting to download YouTube videos results in error "ERROR: YouTube said: Unable to extract video data". This only occurs sometimes and appears to be a bit inconsistent, since attempting to download the target video again seems to work in most cases. Therefore, recreating the problem may take a few tries before the error is generated. Running youtube-dl version 2020.10.30 on macOS.

**Comment by Puffin05** [comment]
Seems like YouTube is testing a new version of their player which is sometimes used instead of the old one, and this new version is not supported by youtube-dl. The problem is being worked on in another fork of youtube-dl:
https://github.com/blackjack4494/yt-dlc/issues/56

**Comment by l1ving** [comment]
I'll see if blackjack4494/yt-dlc#68 gets merged and implement it I guess

**Comment by MidgardSerpent** [comment]
i just checked and there is a new version on the official site and the pip repository that fixed the issue for youtube not downloading for me

**Comment by cybernobie** [comment]
Also Found Working youtube-dl with this issue solved on [gitlab](https://gitlab.com/dstftw/youtube-dl)

**Comment by 91ajames** [comment]
@cybernobie that is the main repository and also with DSTFTW on here github.
L1ving is a backup for changes from there.

**Comment by l1ving** [comment]
This should now be fixed, I merged the changes from gitlab

**Comment by Puffin05** [comment]
Would it be possible to create a release with the fixes? Version 2020.11.01 and version 2020.11.01.1 on [gitlab](https://gitlab.com/dstftw/youtube-dl) both still have the issue (they were created before the fixes were made after all).

**Comment by l1ving** [comment]
The current release has all the fixes this repo applied. There's a pending pull for a different fix.

**Comment by CypherpunkSamurai** [comment]
I'm unable to download playlists. Even with youtube dlc. Probably the new playlist ui needs to be added too.

**Comment by l1ving** [comment]
I've made a new release with the playlist fix

**Comment by kiwiheretic** [comment]
I'm getting this issue also when I try to download with this URL https://www.youtube.com/watch?v=oGzU688xCUs&list=PLN4CJPbz7QROSD6BM-G4f-DlMcX8yNdVW&index=3

[youtube:tab] PLN4CJPbz7QROSD6BM-G4f-DlMcX8yNdVW: Downloading webpage
[download] Downloading playlist: PLN4CJPbz7QROSD6BM-G4f-DlMcX8yNdVW
[youtube:tab] playlist PLN4CJPbz7QROSD6BM-G4f-DlMcX8yNdVW: Downloading 7 videos
[download] Downloading video 1 of 7
[youtube] YGk09nK_xnM: Downloading webpage
ERROR: YGk09nK_xnM: YouTube said: Unable to extract video data

**Comment by l1ving** [comment]
Make a new issue with the template filled out. Youtube had an outage at the time of your comment so it's probably that.
